# set mirror in the last step in order to let automatic build much faster
FROM ubuntu

# necessary tools
RUN apt update && apt install -y ca-certificates vim
# apps
RUN apt install -y gcc g++ python3 python-is-python3 perl
# set mirror
COPY ./sources.list /etc/apt/sources.list
# flush apt
RUN apt update
