name: Docker Image CI

on:
  push:
    paths:
      - .github/workflows
      - Dockerfile
      - Dockerfile.ci
    branches: [ main ]
  pull_request:
    paths:
      - .github/workflows
      - Dockerfile
      - Dockerfile.ci
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sjc0910/ubuntu-cn-utils
    - name: List files
      run: ls -R
        
  build-ci-mode:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.ci --tag sjc0910/ubuntu-cn-utils-ci
    - name: Deploy the Docker image
      run: docker save -o ./ubuntu-cn-utils.tar sjc0910/ubuntu-cn-utils-ci
    - name: List files
      run: ls -R
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: built-docker-image
        path: ./ubuntu-cn-utils.tar
